import type { SolutionPlugin, SolutionStage, SolutionDef } from "./types";

// ─── Customer Support Plugins ─────────────────────────────────────────────────

export const CS_PLUGINS: SolutionPlugin[] = [
  {
    id: "ticket-creation",
    name: "Ticket Creation",
    description: "Creates and organizes support tickets from customer requests received through connected channels.",
    purpose: "Ticket Ingestion",
    category: "Ticket Management",
    logoType: "ticket-creation",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["ticket-creation"],
    capabilities: ["Multi-channel capture", "Field population", "Priority assignment", "Duplicate detection"],
    use: "Turning inbound customer requests into structured support tickets.",
    integrationsWith: ["zendesk", "servicenow", "slack"],
  },
  {
    id: "ticket-classification",
    name: "Ticket Classification",
    description: "Automatically identifies the issue type, category, priority level, and relevant support queue for incoming tickets.",
    purpose: "Issue Classification",
    category: "Ticket Management",
    logoType: "ticket-classification",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["ticket-creation", "routing"],
    capabilities: ["Category detection", "Priority scoring", "Queue assignment", "Urgency flagging"],
    use: "Ensuring tickets reach the right team with accurate classification.",
    integrationsWith: ["zendesk", "servicenow"],
  },
  {
    id: "knowledge-search",
    name: "Knowledge Search",
    description: "Searches approved knowledge sources to find relevant answers, troubleshooting steps, and support documentation for the current issue.",
    purpose: "Knowledge Retrieval",
    category: "Knowledge",
    logoType: "knowledge-search",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["knowledge", "agent-assist"],
    capabilities: ["Article search", "FAQ matching", "Troubleshooting lookup", "Confidence scoring"],
    use: "Surfacing the most relevant information to resolve customer issues faster.",
    integrationsWith: ["confluence", "zendesk"],
  },
  {
    id: "customer-context",
    name: "Customer Context",
    description: "Retrieves relevant customer account details, interaction history, open tickets, and previous resolutions to provide context for each support request.",
    purpose: "Customer History Retrieval",
    category: "Knowledge",
    logoType: "customer-context",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["ticket-creation", "agent-assist"],
    capabilities: ["Account lookup", "Interaction history", "Previous ticket context", "Product usage data"],
    use: "Giving agents full customer context before they respond.",
    integrationsWith: ["zendesk", "salesforce", "hubspot-crm"],
  },
  {
    id: "agent-assist",
    name: "Agent Assist",
    description: "Provides support agents with suggested responses, relevant knowledge articles, and recommended next actions based on the current ticket.",
    purpose: "Agent Guidance",
    category: "Agent Assist",
    logoType: "agent-assist",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["agent-assist"],
    capabilities: ["Response suggestions", "Article recommendations", "Action guidance", "Sentiment detection"],
    use: "Helping agents resolve tickets faster with AI-generated response guidance.",
    integrationsWith: ["zendesk", "slack"],
  },
  {
    id: "response-generation",
    name: "Response Generation",
    description: "Generates context-aware customer responses using approved support information, conversation history, and configured tone guidelines.",
    purpose: "Customer Response Drafting",
    category: "Resolution",
    logoType: "response-generation",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["resolution"],
    capabilities: ["Draft generation", "Tone compliance", "Personalization", "Knowledge grounding"],
    use: "Producing accurate, on-brand responses for agents to review and send.",
    integrationsWith: ["zendesk", "servicenow"],
  },
  {
    id: "ticket-routing",
    name: "Ticket Routing",
    description: "Routes support requests to the appropriate team, queue, or agent based on issue type, priority, customer tier, and business rules.",
    purpose: "Intelligent Routing",
    category: "Ticket Management",
    logoType: "ticket-routing",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["routing"],
    capabilities: ["Rules-based routing", "Skill-based assignment", "Load balancing", "SLA-aware routing"],
    use: "Getting tickets to the right team without manual triage.",
    integrationsWith: ["zendesk", "servicenow", "slack"],
  },
  {
    id: "escalation",
    name: "Escalation",
    description: "Escalates unresolved or high-priority customer issues to the appropriate support team or manager with full context and history.",
    purpose: "Issue Escalation",
    category: "Escalation",
    logoType: "escalation",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["escalation"],
    capabilities: ["Threshold detection", "Manager notification", "Context packaging", "SLA breach alerting"],
    use: "Ensuring critical issues are escalated to the right person before SLAs are breached.",
    integrationsWith: ["zendesk", "slack", "servicenow"],
  },
  {
    id: "customer-notification",
    name: "Customer Notification",
    description: "Sends customers automated updates, confirmations, status changes, reminders, and resolution notifications throughout the support process.",
    purpose: "Proactive Customer Updates",
    category: "Communication",
    logoType: "customer-notification",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["routing", "resolution", "follow-up"],
    capabilities: ["Status updates", "Resolution confirmation", "SLA notifications", "Follow-up messages"],
    use: "Keeping customers informed at every stage without manual communication effort.",
    integrationsWith: ["zendesk", "slack"],
  },
  {
    id: "support-summary",
    name: "Support Summary",
    description: "Summarizes customer conversations, issue history, actions taken, resolution status, and next steps for agent review and records.",
    purpose: "Conversation Summary",
    category: "Reporting",
    logoType: "support-summary",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["resolution", "follow-up"],
    capabilities: ["Conversation summary", "Action log", "Resolution documentation", "Handoff notes"],
    use: "Producing a structured record of each support interaction for agent review and future reference.",
    integrationsWith: ["zendesk", "confluence"],
  },
  {
    id: "support-analytics",
    name: "Support Analytics",
    description: "Analyzes support ticket volumes, resolution times, CSAT trends, escalation rates, and agent performance to surface actionable insights.",
    purpose: "Support Performance Insights",
    category: "Reporting",
    logoType: "support-analytics",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["analytics"],
    capabilities: ["Volume analysis", "Resolution time tracking", "CSAT monitoring", "Escalation reporting"],
    use: "Giving support managers the data to improve team performance and reduce resolution times.",
    integrationsWith: ["zendesk", "servicenow"],
  },
  // ── Integrations ─────────────────────────────────────────────────────────
  {
    id: "zendesk",
    name: "Zendesk",
    description: "Syncs tickets, customer data, and support activity between SoloBuildAI and the Zendesk customer support platform.",
    purpose: "Support Platform",
    category: "Integration",
    logoType: "zendesk",
    tier: "Integration · Tier 1",
    status: "Quick-start",
    workflowStages: ["ticket-creation", "routing", "resolution", "analytics"],
    capabilities: ["Ticket sync", "Customer data access", "Workflow triggers"],
    method: "Zendesk REST API",
    authentication: "OAuth 2.0",
    use: "Primary support platform integration for ticket and customer management.",
  },
  {
    id: "servicenow-cs",
    name: "ServiceNow",
    description: "Routes support workflows, manages incidents, and tracks service requests through ServiceNow's ITSM platform.",
    purpose: "ITSM & Service Management",
    category: "Integration",
    logoType: "servicenow",
    tier: "Integration · Tier 2",
    status: "Account access required",
    workflowStages: ["ticket-creation", "routing", "escalation"],
    capabilities: ["Incident management", "Request routing", "SLA tracking"],
    method: "ServiceNow REST API",
    authentication: "OAuth 2.0",
    use: "Enterprise service management integration for structured support workflows.",
  },
  {
    id: "slack-cs",
    name: "Slack",
    description: "Sends real-time support notifications, escalation alerts, and team updates to appropriate Slack channels.",
    purpose: "Team Notifications",
    category: "Integration",
    logoType: "slack",
    tier: "Integration · Tier 2",
    status: "Quick-start",
    workflowStages: ["routing", "escalation", "resolution"],
    capabilities: ["Channel alerts", "Escalation notifications", "Status updates"],
    method: "Slack API",
    authentication: "OAuth 2.0",
    use: "Real-time support team communication and escalation alerts.",
  },
];

export const ALL_CS_PLUGINS = CS_PLUGINS;

// ─── Support Workflow Stages ──────────────────────────────────────────────────

export const CS_STAGES: SolutionStage[] = [
  {
    id: "ticket-creation",
    number: "01",
    title: "Ticket Creation",
    description: "Capture and structure the customer request.",
    pluginIds: ["ticket-creation", "ticket-classification", "customer-context"],
  },
  {
    id: "routing",
    number: "02",
    title: "Routing & Classification",
    description: "Route to the right team or queue.",
    pluginIds: ["ticket-classification", "ticket-routing", "customer-notification"],
  },
  {
    id: "knowledge",
    number: "03",
    title: "Knowledge Retrieval",
    description: "Find relevant answers and documentation.",
    pluginIds: ["knowledge-search", "customer-context"],
  },
  {
    id: "agent-assist",
    number: "04",
    title: "Agent Assist",
    description: "Guide agents with AI-generated suggestions.",
    pluginIds: ["agent-assist", "knowledge-search", "customer-context"],
  },
  {
    id: "resolution",
    number: "05",
    title: "Resolution",
    description: "Generate and send the customer response.",
    pluginIds: ["response-generation", "customer-notification", "support-summary"],
  },
  {
    id: "escalation",
    number: "06",
    title: "Escalation",
    description: "Escalate unresolved or high-priority issues.",
    pluginIds: ["escalation", "slack-cs", "customer-notification"],
  },
  {
    id: "follow-up",
    number: "07",
    title: "Follow-up",
    description: "Confirm resolution and gather feedback.",
    pluginIds: ["customer-notification", "support-summary"],
  },
  {
    id: "analytics",
    number: "08",
    title: "Support Analytics",
    description: "Analyze performance and identify improvements.",
    pluginIds: ["support-analytics", "zendesk"],
  },
];

// ─── Customer Support Solution Definition ─────────────────────────────────────

export const CS_SOLUTION: SolutionDef = {
  id: "customer-support",
  slug: "customer-support",
  name: "Customer Support",
  tagline: "Every request resolved.",
  description: "AI agents to automate ticket management, knowledge retrieval, agent assistance, and customer communication — so your team can focus on complex issues that need human judgment.",
  eyebrow: "Solutions / Customer Support",
  heroQuote: "AI agents that classify tickets, guide agents, and keep customers informed.",
  stats: [
    { value: "8",   label: "Support Workflows" },
    { value: "11+", label: "Ready-to-use Plugins" },
    { value: "3+",  label: "Integrations" },
    { value: "40%", label: "Faster Resolution" },
  ],
  processes: [
    {
      id: "support-workflow",
      title: "Support Workflow",
      description: "End-to-end customer issue resolution with AI assistance.",
      pluginCount: "8 plugins",
      integrationCount: "3 integrations",
      href: "/solutions/customer-support/support-workflow",
      icon: "support",
      live: true,
    },
    {
      id: "knowledge-management",
      title: "Knowledge Management",
      description: "Surface the right information for every customer interaction.",
      pluginCount: "3 plugins",
      integrationCount: "2 integrations",
      href: "/solutions/customer-support/knowledge-resolution",
      icon: "book",
    },
    {
      id: "escalation-management",
      title: "Escalation Management",
      description: "Intelligently escalate issues before SLAs are breached.",
      pluginCount: "3 plugins",
      integrationCount: "2 integrations",
      href: "/solutions/customer-support/escalation",
      icon: "alert",
    },
    {
      id: "support-analytics",
      title: "Support Analytics",
      description: "Understand performance, trends, and improvement opportunities.",
      pluginCount: "2 plugins",
      integrationCount: "2 integrations",
      href: "/solutions/customer-support/support-analytics",
      icon: "chart",
    },
  ],
  integrationNames: ["Zendesk", "ServiceNow", "Slack", "Confluence", "Salesforce", "HubSpot"],
};
