/**
 * HR Workflow Plugin & Stage Data
 *
 * Central data file for all 7 HR workflows.
 * Each workflow exports its own plugins array and stages array,
 * plus a combined ALL_ export used by SolutionWorkflowPage.
 *
 * LogoTypes reuse the SolutionLogoType union from types.ts.
 * Where a specific logoType doesn't yet exist for HR-specific
 * native plugins, we use the closest matching existing type —
 * replaceable by adding to PluginLogo later.
 */

import type { SolutionPlugin, SolutionStage } from "./types";

// ─────────────────────────────────────────────────────────────────────────────
// TALENT ACQUISITION  (migrated from lib/talent-acquisition/plugins.ts)
// ─────────────────────────────────────────────────────────────────────────────

export const TA_PLUGINS: SolutionPlugin[] = [
  {
    id: "jd-analyzer",
    name: "Job Description Analyzer",
    description: "Analyzes job descriptions and extracts role requirements, required skills, experience levels, and screening criteria to guide the hiring workflow.",
    purpose: "Role Requirements Analysis",
    category: "Analysis",
    logoType: "jd-analyzer",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["description"],
    capabilities: ["Requirement extraction", "Skill identification", "Criteria structuring", "Seniority detection"],
    use: "Structuring role criteria before sourcing and screening begins.",
    integrationsWith: ["confluence", "jira"],
  },
  {
    id: "candidate-sourcing",
    name: "Candidate Sourcing",
    description: "Finds and imports candidate profiles from connected recruiting sources into the active hiring workflow, ranked by relevance to the extracted role criteria.",
    purpose: "Candidate Discovery",
    category: "Sourcing",
    logoType: "candidate-sourcing",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["sourcing"],
    capabilities: ["Profile discovery", "Source connection", "Relevance ranking", "Pipeline import"],
    use: "Populating the candidate pipeline from connected sources.",
    integrationsWith: ["workable", "ashby", "hubspot-crm"],
  },
  {
    id: "resume-parser",
    name: "Resume Parser",
    description: "Extracts structured candidate information including skills, work history, education, certifications, and contact details from unstructured resume documents.",
    purpose: "Resume Data Extraction",
    category: "Analysis",
    logoType: "resume-parser",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["resume-screening"],
    capabilities: ["Skills extraction", "Experience parsing", "Education recognition", "Contact structuring"],
    use: "Converting raw resumes into structured candidate profiles.",
    integrationsWith: ["workable", "ashby"],
  },
  {
    id: "resume-screening",
    name: "Resume Screening",
    description: "Compares candidate resumes against the role requirements and qualification criteria, identifying relevant qualifications and flagging gaps.",
    purpose: "Resume Qualification Matching",
    category: "Screening",
    logoType: "resume-screening",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["resume-screening"],
    capabilities: ["Requirement matching", "Gap identification", "Qualification flagging", "Criteria scoring"],
    use: "Filtering candidates to those meeting minimum role requirements.",
    integrationsWith: ["workable", "ashby", "jira"],
  },
  {
    id: "candidate-scoring",
    name: "Candidate Scoring",
    description: "Scores candidates against role-specific criteria to produce a ranked shortlist, helping recruiters prioritize the most relevant profiles before voice screening.",
    purpose: "Candidate Prioritization",
    category: "Screening",
    logoType: "candidate-scoring",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["resume-screening", "scoring"],
    capabilities: ["Multi-criteria scoring", "Weighted ranking", "Threshold filtering", "Shortlist generation"],
    use: "Producing a ranked candidate shortlist before AI voice screening.",
    integrationsWith: ["workable", "ashby"],
  },
  {
    id: "voice-screening",
    name: "AI Voice Screening",
    description: "Conducts automated conversational voice calls with candidates, asking role-specific questions and evaluating responses against pre-defined screening criteria.",
    purpose: "Automated Voice Conversations",
    category: "Screening",
    logoType: "voice-screening",
    tier: "Native · Core Capability",
    status: "Active",
    workflowStages: ["voice"],
    capabilities: ["Outbound voice calls", "Role-specific questioning", "Response capture", "Conversation transcription"],
    use: "Engaging shortlisted candidates at scale through AI-conducted phone conversations.",
    integrationsWith: ["slack", "workable"],
  },
  {
    id: "call-assessment",
    name: "Call Assessment",
    description: "Analyzes recorded screening conversations and generates a structured candidate assessment covering communication quality, role fit, and red flags.",
    purpose: "Conversation Analysis",
    category: "Analysis",
    logoType: "call-assessment",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["call-assessment"],
    capabilities: ["Response analysis", "Communication scoring", "Red flag detection", "Assessment generation"],
    use: "Turning voice screening transcripts into structured recruiter-ready assessments.",
    integrationsWith: ["workable", "ashby"],
  },
  {
    id: "interview-scheduling",
    name: "Interview Scheduling",
    description: "Coordinates candidate and interviewer availability across connected calendar systems and creates confirmed interview schedules without manual back-and-forth.",
    purpose: "Availability Coordination",
    category: "Scheduling",
    logoType: "interview-scheduling",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["interview"],
    capabilities: ["Availability matching", "Calendar sync", "Invite dispatch", "Reminder scheduling"],
    use: "Automating interview coordination after candidate qualification.",
    integrationsWith: ["google-calendar", "ashby", "workable"],
  },
  {
    id: "candidate-communication",
    name: "Candidate Communication",
    description: "Sends automated, contextually appropriate updates to candidates throughout the hiring process including invitations, status updates, and follow-ups.",
    purpose: "Candidate Messaging",
    category: "Communication",
    logoType: "candidate-communication",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["sourcing", "voice", "interview"],
    capabilities: ["Status notifications", "Invitation dispatch", "Follow-up messages", "Reminder automation"],
    use: "Keeping candidates informed and engaged throughout the hiring workflow.",
    integrationsWith: ["slack", "workable"],
  },
  {
    id: "screening-report",
    name: "Screening Report",
    description: "Combines resume screening and voice screening results into a single structured candidate report for recruiter review, including scores and recommended actions.",
    purpose: "Candidate Summary Report",
    category: "Reporting",
    logoType: "screening-report",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["report"],
    capabilities: ["Resume summary", "Voice assessment inclusion", "Score aggregation", "Action recommendations"],
    use: "Giving recruiters a complete view of each candidate before hiring decisions.",
    integrationsWith: ["workable", "ashby", "jira"],
  },
  // Integrations
  {
    id: "ta-google-calendar",
    name: "Google Calendar",
    description: "Connects to Google Calendar for interviewer availability lookup and confirmed interview event creation.",
    purpose: "Calendar & Scheduling",
    category: "Integration",
    logoType: "google-calendar",
    tier: "Integration · Tier 1",
    status: "Quick-start",
    workflowStages: ["interview"],
    capabilities: ["Availability lookup", "Event creation", "Invite dispatch"],
    method: "Google Calendar API v3",
    authentication: "OAuth 2.0",
    use: "Interview scheduling and calendar coordination.",
    integrationsWith: ["interview-scheduling"],
  },
  {
    id: "ta-jira",
    name: "Jira",
    description: "Creates and tracks hiring tasks, workflow handoffs, and recruiter actions inside Jira for full team visibility.",
    purpose: "Task & Workflow Tracking",
    category: "Integration",
    logoType: "jira",
    tier: "Integration · Tier 1",
    status: "Quick-start",
    workflowStages: ["description", "sourcing", "resume-screening", "interview", "hire"],
    capabilities: ["Task creation", "Workflow tracking", "Team handoffs"],
    method: "Jira Cloud REST API",
    authentication: "OAuth 2.0",
    use: "Recruiting task and workflow management.",
  },
];

export const ALL_TA_PLUGINS = TA_PLUGINS;

export const TA_STAGES: SolutionStage[] = [
  { id: "description",      number: "01", title: "Job Description",  description: "Understand the role and extract hiring criteria.", pluginIds: ["jd-analyzer", "ta-jira"] },
  { id: "sourcing",         number: "02", title: "Candidate Sourcing", description: "Find and engage relevant candidates.",             pluginIds: ["candidate-sourcing", "candidate-communication"] },
  { id: "resume-screening", number: "03", title: "Resume Screening",  description: "Parse and rank candidates against the role.",       pluginIds: ["resume-parser", "resume-screening", "candidate-scoring"] },
  { id: "voice",            number: "04", title: "AI Voice Screening", description: "Conduct structured AI voice conversations.",        pluginIds: ["voice-screening", "candidate-communication"] },
  { id: "call-assessment",  number: "05", title: "Call Assessment",   description: "Analyze conversations and generate assessments.",   pluginIds: ["call-assessment", "screening-report"] },
  { id: "interview",        number: "06", title: "Interview",          description: "Coordinate schedules and conduct interviews.",      pluginIds: ["interview-scheduling", "ta-google-calendar", "candidate-communication"] },
  { id: "report",           number: "07", title: "Recruiter Review",  description: "Give recruiters a complete candidate view.",        pluginIds: ["screening-report", "ta-jira"] },
  { id: "hire",             number: "08", title: "Shortlist & Hire",  description: "Move the right candidate forward.",                 pluginIds: ["ta-jira"] },
];

// ─────────────────────────────────────────────────────────────────────────────
// EMPLOYEE ONBOARDING
// ─────────────────────────────────────────────────────────────────────────────

export const ONBOARDING_PLUGINS: SolutionPlugin[] = [
  {
    id: "onboard-intake",
    name: "Onboarding Intake",
    description: "Collects new hire information, role details, and start requirements to initialize the onboarding workflow.",
    purpose: "New Hire Data Collection",
    category: "Request Management",
    logoType: "it-request-intake",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["intake"],
    capabilities: ["Data collection", "Profile creation", "Requirement capture"],
    use: "Starting the onboarding process with all necessary new hire information.",
  },
  {
    id: "onboard-task-creation",
    name: "Onboarding Task Creation",
    description: "Generates and assigns a structured checklist of onboarding tasks for HR, IT, and the new hire's team.",
    purpose: "Task Assignment",
    category: "Automation",
    logoType: "task-creation",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["task-setup"],
    capabilities: ["Checklist generation", "Task assignment", "Deadline setting", "Team notification"],
    use: "Creating and distributing onboarding tasks across all relevant stakeholders.",
    integrationsWith: ["servicenow", "jira"],
  },
  {
    id: "onboard-access-provisioning",
    name: "Access Provisioning",
    description: "Requests and tracks provisioning of system access, tools, and application credentials for the new hire.",
    purpose: "Access Setup",
    category: "Access Management",
    logoType: "user-access-management",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["access"],
    capabilities: ["Access request", "Tool provisioning", "Credential setup", "Approval tracking"],
    use: "Ensuring new hires have access to all required systems on day one.",
    integrationsWith: ["servicenow"],
  },
  {
    id: "onboard-knowledge",
    name: "Knowledge & Resources",
    description: "Surfaces relevant onboarding documentation, company policies, role guides, and training materials for the new hire.",
    purpose: "Resource Delivery",
    category: "Knowledge",
    logoType: "knowledge-retrieval",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["learning"],
    capabilities: ["Document surfacing", "Policy delivery", "Training material assignment", "Progress tracking"],
    use: "Giving new hires the information they need to ramp up effectively.",
    integrationsWith: ["confluence"],
  },
  {
    id: "onboard-communication",
    name: "Onboarding Communication",
    description: "Sends automated welcome messages, task reminders, check-in prompts, and completion confirmations throughout onboarding.",
    purpose: "New Hire Communication",
    category: "Communication",
    logoType: "candidate-communication",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["intake", "task-setup", "learning", "completion"],
    capabilities: ["Welcome messages", "Reminders", "Check-in automation", "Completion notifications"],
    use: "Keeping new hires informed and supported throughout the onboarding period.",
    integrationsWith: ["slack", "microsoft-teams"],
  },
  {
    id: "onboard-summary",
    name: "Onboarding Summary",
    description: "Generates a completion report summarizing completed tasks, pending items, access granted, and next steps for HR review.",
    purpose: "Completion Reporting",
    category: "Reporting",
    logoType: "it-summary",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["completion"],
    capabilities: ["Task completion summary", "Access log", "Pending items", "Next step recommendations"],
    use: "Giving HR a complete view of each new hire's onboarding status.",
    integrationsWith: ["servicenow", "confluence"],
  },
];

export const ALL_ONBOARDING_PLUGINS = ONBOARDING_PLUGINS;

export const ONBOARDING_STAGES: SolutionStage[] = [
  { id: "intake",     number: "01", title: "New Hire Intake",    description: "Collect new hire details and initialize workflow.", pluginIds: ["onboard-intake", "onboard-communication"] },
  { id: "task-setup", number: "02", title: "Task Setup",          description: "Generate and assign onboarding checklist.",         pluginIds: ["onboard-task-creation"] },
  { id: "access",     number: "03", title: "Access Provisioning", description: "Set up system access and tools.",                   pluginIds: ["onboard-access-provisioning"] },
  { id: "learning",   number: "04", title: "Knowledge & Training", description: "Deliver documentation and training materials.",    pluginIds: ["onboard-knowledge", "onboard-communication"] },
  { id: "completion", number: "05", title: "Completion & Review", description: "Confirm completion and review progress.",            pluginIds: ["onboard-summary", "onboard-communication"] },
];

// ─────────────────────────────────────────────────────────────────────────────
// LEARNING & DEVELOPMENT  (shared plugin set)
// ─────────────────────────────────────────────────────────────────────────────

export const LD_PLUGINS: SolutionPlugin[] = [
  {
    id: "ld-needs-analysis",
    name: "Learning Needs Analysis",
    description: "Identifies skill gaps and learning needs for individuals and teams based on role requirements and performance data.",
    purpose: "Skill Gap Identification",
    category: "Analysis",
    logoType: "jd-analyzer",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["analysis"],
    capabilities: ["Skill gap detection", "Role requirement mapping", "Team analysis", "Priority identification"],
    use: "Determining what learning is needed before building development plans.",
  },
  {
    id: "ld-content-curation",
    name: "Content Curation",
    description: "Identifies and organizes relevant learning content, courses, and resources matched to the identified skill gaps and learning objectives.",
    purpose: "Learning Content Matching",
    category: "Knowledge",
    logoType: "knowledge-retrieval",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["content"],
    capabilities: ["Course matching", "Content organization", "Learning path creation", "Resource curation"],
    use: "Delivering the right learning content to the right people.",
    integrationsWith: ["confluence"],
  },
  {
    id: "ld-assignment",
    name: "Learning Assignment",
    description: "Assigns learning plans, courses, and development goals to individuals and teams based on their role, gaps, and learning objectives.",
    purpose: "Development Plan Assignment",
    category: "Automation",
    logoType: "task-creation",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["assignment"],
    capabilities: ["Plan assignment", "Goal setting", "Deadline management", "Manager notification"],
    use: "Distributing personalized development plans to employees and their managers.",
    integrationsWith: ["slack", "microsoft-teams"],
  },
  {
    id: "ld-progress-tracking",
    name: "Progress Tracking",
    description: "Monitors completion of learning activities, tracks progress against development goals, and surfaces at-risk learners.",
    purpose: "Learning Progress Monitoring",
    category: "Reporting",
    logoType: "service-analytics",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["tracking"],
    capabilities: ["Completion tracking", "Goal progress", "At-risk identification", "Manager reporting"],
    use: "Keeping managers and HR informed on learning progress across the organization.",
  },
  {
    id: "ld-communication",
    name: "Learning Communication",
    description: "Sends automated learning reminders, completion celebrations, and development plan updates to employees and managers.",
    purpose: "Learner Communication",
    category: "Communication",
    logoType: "candidate-communication",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["assignment", "tracking"],
    capabilities: ["Reminders", "Progress notifications", "Manager updates", "Completion messages"],
    use: "Keeping learners engaged and managers informed throughout development programmes.",
    integrationsWith: ["slack", "microsoft-teams"],
  },
];

export const ALL_LD_PLUGINS = LD_PLUGINS;

export const LD_STAGES: SolutionStage[] = [
  { id: "analysis",   number: "01", title: "Needs Analysis",   description: "Identify skill gaps and learning priorities.", pluginIds: ["ld-needs-analysis"] },
  { id: "content",    number: "02", title: "Content Curation", description: "Match learning content to identified needs.",  pluginIds: ["ld-content-curation"] },
  { id: "assignment", number: "03", title: "Plan Assignment",  description: "Assign development plans and goals.",          pluginIds: ["ld-assignment", "ld-communication"] },
  { id: "tracking",   number: "04", title: "Progress Tracking", description: "Monitor completion and flag at-risk learners.", pluginIds: ["ld-progress-tracking", "ld-communication"] },
];

// ─────────────────────────────────────────────────────────────────────────────
// PERFORMANCE & REVIEWS
// ─────────────────────────────────────────────────────────────────────────────

export const PERF_PLUGINS: SolutionPlugin[] = [
  {
    id: "perf-cycle-setup",
    name: "Review Cycle Setup",
    description: "Configures review cycles, sets timelines, assigns participants, and notifies employees and managers of upcoming review periods.",
    purpose: "Cycle Configuration",
    category: "Automation",
    logoType: "task-creation",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["setup"],
    capabilities: ["Cycle configuration", "Participant assignment", "Timeline setting", "Notification dispatch"],
    use: "Launching structured performance review cycles across the organization.",
    integrationsWith: ["slack", "microsoft-teams"],
  },
  {
    id: "perf-feedback-collection",
    name: "Feedback Collection",
    description: "Collects structured feedback from peers, managers, and direct reports as part of multi-source performance reviews.",
    purpose: "Multi-Source Feedback",
    category: "Analysis",
    logoType: "call-assessment",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["feedback"],
    capabilities: ["Peer feedback", "Manager feedback", "Self-assessment", "Structured capture"],
    use: "Gathering comprehensive performance feedback from all relevant stakeholders.",
    integrationsWith: ["slack", "microsoft-teams"],
  },
  {
    id: "perf-summary",
    name: "Performance Summary",
    description: "Synthesizes collected feedback and performance data into a structured review document for manager and employee use.",
    purpose: "Review Document Generation",
    category: "Reporting",
    logoType: "screening-report",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["review"],
    capabilities: ["Feedback synthesis", "Rating aggregation", "Trend identification", "Summary generation"],
    use: "Producing structured review documents that support meaningful performance conversations.",
  },
  {
    id: "perf-goal-setting",
    name: "Goal Setting",
    description: "Facilitates structured goal creation for the next review period, aligned to role expectations and organizational objectives.",
    purpose: "Development Goal Creation",
    category: "Automation",
    logoType: "approval-workflow",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["goals"],
    capabilities: ["Goal creation", "OKR alignment", "Manager approval", "Goal tracking"],
    use: "Setting clear, measurable development goals for the next performance period.",
  },
  {
    id: "perf-communication",
    name: "Performance Communication",
    description: "Sends automated reminders, review invites, deadline alerts, and completion confirmations throughout the review cycle.",
    purpose: "Review Communication",
    category: "Communication",
    logoType: "it-notification",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["setup", "feedback", "review"],
    capabilities: ["Deadline reminders", "Review invites", "Completion alerts", "Status updates"],
    use: "Keeping employees and managers informed throughout the performance review cycle.",
    integrationsWith: ["slack", "microsoft-teams"],
  },
];

export const ALL_PERF_PLUGINS = PERF_PLUGINS;

export const PERF_STAGES: SolutionStage[] = [
  { id: "setup",    number: "01", title: "Cycle Setup",       description: "Configure review cycles and notify participants.", pluginIds: ["perf-cycle-setup", "perf-communication"] },
  { id: "feedback", number: "02", title: "Feedback Collection", description: "Gather structured multi-source feedback.",          pluginIds: ["perf-feedback-collection", "perf-communication"] },
  { id: "review",   number: "03", title: "Review & Summary",  description: "Synthesize feedback into review documents.",        pluginIds: ["perf-summary", "perf-communication"] },
  { id: "goals",    number: "04", title: "Goal Setting",      description: "Set development goals for the next period.",        pluginIds: ["perf-goal-setting"] },
];

// ─────────────────────────────────────────────────────────────────────────────
// PAYROLL & BENEFITS  (thin data set — forward-looking)
// ─────────────────────────────────────────────────────────────────────────────

export const PAYROLL_PLUGINS: SolutionPlugin[] = [
  {
    id: "payroll-data-collection",
    name: "Payroll Data Collection",
    description: "Gathers and validates payroll-relevant employee data including hours, deductions, and compensation changes before processing.",
    purpose: "Payroll Data Validation",
    category: "Analysis",
    logoType: "resume-parser",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["data-collection"],
    capabilities: ["Data gathering", "Validation", "Change detection", "Exception flagging"],
    use: "Ensuring payroll data is complete and accurate before processing.",
  },
  {
    id: "payroll-change-management",
    name: "Compensation Change Management",
    description: "Processes and routes compensation adjustments, promotions, and role changes through the required approval and payroll update workflow.",
    purpose: "Compensation Updates",
    category: "Automation",
    logoType: "approval-workflow",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["approvals"],
    capabilities: ["Change routing", "Approval tracking", "Effective date management", "Payroll sync"],
    use: "Managing compensation changes through structured approval and update workflows.",
    integrationsWith: ["servicenow"],
  },
  {
    id: "benefits-enrollment",
    name: "Benefits Enrollment",
    description: "Guides employees through benefits selection, answers eligibility questions, and submits enrolment decisions to connected benefits systems.",
    purpose: "Benefits Administration",
    category: "Automation",
    logoType: "service-catalog",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["benefits"],
    capabilities: ["Benefits guidance", "Eligibility checking", "Enrolment submission", "Confirmation"],
    use: "Simplifying the benefits enrolment process for employees.",
  },
  {
    id: "payroll-communication",
    name: "Payroll Communication",
    description: "Sends automated payroll confirmations, benefits updates, deadline reminders, and exception notifications to employees and HR.",
    purpose: "Employee Pay Communication",
    category: "Communication",
    logoType: "it-notification",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["data-collection", "approvals", "benefits"],
    capabilities: ["Pay confirmations", "Deadline reminders", "Exception alerts", "Benefits updates"],
    use: "Keeping employees and HR informed about payroll and benefits activity.",
    integrationsWith: ["slack"],
  },
];

export const ALL_PAYROLL_PLUGINS = PAYROLL_PLUGINS;

export const PAYROLL_STAGES: SolutionStage[] = [
  { id: "data-collection", number: "01", title: "Data Collection",  description: "Gather and validate payroll data.",         pluginIds: ["payroll-data-collection"] },
  { id: "approvals",       number: "02", title: "Change Approvals", description: "Route compensation changes for approval.",   pluginIds: ["payroll-change-management", "payroll-communication"] },
  { id: "benefits",        number: "03", title: "Benefits",         description: "Guide benefits selection and enrolment.",    pluginIds: ["benefits-enrollment", "payroll-communication"] },
];

// ─────────────────────────────────────────────────────────────────────────────
// EMPLOYEE SUPPORT
// ─────────────────────────────────────────────────────────────────────────────

export const EMP_SUPPORT_PLUGINS: SolutionPlugin[] = [
  {
    id: "hr-request-intake",
    name: "HR Request Intake",
    description: "Understands employee HR questions and service requests from natural language and converts them into structured support cases.",
    purpose: "Request Understanding",
    category: "Request Management",
    logoType: "it-request-intake",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["intake"],
    capabilities: ["NL understanding", "Request classification", "Case creation", "Urgency detection"],
    use: "Turning unstructured employee HR questions into actionable support cases.",
    integrationsWith: ["servicenow", "slack"],
  },
  {
    id: "hr-knowledge-search",
    name: "HR Knowledge Search",
    description: "Searches HR policy documents, employee handbooks, and approved knowledge sources to find accurate answers to employee questions.",
    purpose: "HR Knowledge Retrieval",
    category: "Knowledge",
    logoType: "it-knowledge-search",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["knowledge"],
    capabilities: ["Policy lookup", "Handbook search", "Benefits information", "Procedure retrieval"],
    use: "Answering employee HR questions using approved organizational knowledge.",
    integrationsWith: ["confluence"],
  },
  {
    id: "hr-response-generation",
    name: "HR Response Generation",
    description: "Generates clear, accurate responses to employee HR questions grounded in approved policies and knowledge sources.",
    purpose: "Response Drafting",
    category: "Resolution",
    logoType: "email-response-generator",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["resolution"],
    capabilities: ["Policy-grounded responses", "Tone compliance", "Personalization", "Accuracy checking"],
    use: "Providing employees with accurate, timely answers to HR questions.",
    integrationsWith: ["slack", "microsoft-teams"],
  },
  {
    id: "hr-escalation",
    name: "HR Escalation",
    description: "Escalates complex or sensitive HR requests to the appropriate HR specialist or manager with full context.",
    purpose: "HR Case Escalation",
    category: "Escalation",
    logoType: "it-escalation",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["escalation"],
    capabilities: ["Complexity detection", "Specialist routing", "Context handoff", "Priority enforcement"],
    use: "Ensuring complex HR cases reach the right HR professional with all necessary context.",
    integrationsWith: ["slack", "servicenow"],
  },
  {
    id: "hr-support-summary",
    name: "HR Support Summary",
    description: "Summarizes the employee request, information provided, actions taken, and resolution status for HR records.",
    purpose: "Case Documentation",
    category: "Reporting",
    logoType: "it-summary",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["resolution"],
    capabilities: ["Case summary", "Action log", "Resolution documentation", "Record keeping"],
    use: "Maintaining accurate records of all employee HR support interactions.",
    integrationsWith: ["servicenow", "confluence"],
  },
];

export const ALL_EMP_SUPPORT_PLUGINS = EMP_SUPPORT_PLUGINS;

export const EMP_SUPPORT_STAGES: SolutionStage[] = [
  { id: "intake",     number: "01", title: "Request Intake",   description: "Understand and classify the employee request.", pluginIds: ["hr-request-intake"] },
  { id: "knowledge",  number: "02", title: "Knowledge Search", description: "Find relevant HR policies and information.",     pluginIds: ["hr-knowledge-search"] },
  { id: "resolution", number: "03", title: "Resolution",       description: "Generate an accurate, policy-grounded response.", pluginIds: ["hr-response-generation", "hr-support-summary"] },
  { id: "escalation", number: "04", title: "Escalation",       description: "Route complex cases to HR specialists.",          pluginIds: ["hr-escalation"] },
];

// ─────────────────────────────────────────────────────────────────────────────
// OFFBOARDING
// ─────────────────────────────────────────────────────────────────────────────

export const OFFBOARDING_PLUGINS: SolutionPlugin[] = [
  {
    id: "offboard-initiation",
    name: "Offboarding Initiation",
    description: "Initiates the offboarding workflow when a departure is confirmed, collecting leaving date, reason, and required handover details.",
    purpose: "Departure Processing",
    category: "Request Management",
    logoType: "it-request-intake",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["initiation"],
    capabilities: ["Departure capture", "Date processing", "Handover identification", "Stakeholder notification"],
    use: "Starting the offboarding process with all required departure information.",
    integrationsWith: ["servicenow"],
  },
  {
    id: "offboard-access-revocation",
    name: "Access Revocation",
    description: "Coordinates the revocation of system access, application credentials, and physical access rights on or before the departure date.",
    purpose: "Access Removal",
    category: "Access Management",
    logoType: "user-access-management",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["access"],
    capabilities: ["Access revocation", "Credential removal", "Physical access management", "Completion verification"],
    use: "Ensuring all system and physical access is removed on departure.",
    integrationsWith: ["servicenow"],
  },
  {
    id: "offboard-knowledge-transfer",
    name: "Knowledge Transfer",
    description: "Identifies critical knowledge the departing employee holds, surfaces relevant documentation, and creates handover notes.",
    purpose: "Knowledge Handover",
    category: "Knowledge",
    logoType: "knowledge-retrieval",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["handover"],
    capabilities: ["Knowledge identification", "Documentation surfacing", "Handover note creation", "Successor assignment"],
    use: "Capturing and transferring critical knowledge before the employee departs.",
    integrationsWith: ["confluence"],
  },
  {
    id: "offboard-communication",
    name: "Offboarding Communication",
    description: "Sends structured communications to the departing employee, their team, and HR throughout the offboarding process.",
    purpose: "Departure Communication",
    category: "Communication",
    logoType: "candidate-communication",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["initiation", "handover", "completion"],
    capabilities: ["Employee communication", "Team notification", "IT coordination", "HR updates"],
    use: "Coordinating communication across all parties involved in the offboarding.",
    integrationsWith: ["slack", "microsoft-teams"],
  },
  {
    id: "offboard-summary",
    name: "Offboarding Summary",
    description: "Generates a completion report confirming all offboarding tasks are complete, access revoked, and any outstanding items.",
    purpose: "Offboarding Completion Report",
    category: "Reporting",
    logoType: "it-summary",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["completion"],
    capabilities: ["Task completion verification", "Access revocation confirmation", "Outstanding items", "HR sign-off"],
    use: "Confirming all offboarding obligations have been fulfilled.",
    integrationsWith: ["servicenow", "confluence"],
  },
];

export const ALL_OFFBOARDING_PLUGINS = OFFBOARDING_PLUGINS;

export const OFFBOARDING_STAGES: SolutionStage[] = [
  { id: "initiation", number: "01", title: "Initiation",         description: "Confirm departure and initialize workflow.",   pluginIds: ["offboard-initiation", "offboard-communication"] },
  { id: "access",     number: "02", title: "Access Revocation",  description: "Revoke system and physical access.",            pluginIds: ["offboard-access-revocation"] },
  { id: "handover",   number: "03", title: "Knowledge Handover", description: "Transfer critical knowledge and responsibilities.", pluginIds: ["offboard-knowledge-transfer", "offboard-communication"] },
  { id: "completion", number: "04", title: "Completion",         description: "Confirm all offboarding tasks complete.",        pluginIds: ["offboard-summary", "offboard-communication"] },
];
