import type { SolutionPlugin, SolutionStage } from "./types";

export const IT_EMAIL_PLUGINS: SolutionPlugin[] = [
  {
    id: "email-intake",
    name: "Email Intake",
    description: "Receives and processes incoming operational emails from configured mailboxes, making them available for classification and routing.",
    purpose: "Email Ingestion",
    category: "Automation",
    logoType: "email-intake",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["email-intake"],
    capabilities: ["Mailbox monitoring", "Email parsing", "Attachment handling", "Threading"],
    use: "Bringing operational emails into the automation workflow from configured mailboxes.",
    integrationsWith: ["gmail", "outlook"],
  },
  {
    id: "email-classification",
    name: "Email Classification",
    description: "Identifies the purpose, category, urgency, and routing requirements of each incoming email based on its content and context.",
    purpose: "Email Categorization",
    category: "Automation",
    logoType: "email-classification",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["classification"],
    capabilities: ["Intent detection", "Category assignment", "Urgency scoring", "Routing flag"],
    use: "Ensuring every email is correctly categorized before further processing or routing.",
    integrationsWith: ["gmail", "outlook"],
  },
  {
    id: "request-extraction",
    name: "Request Extraction",
    description: "Extracts structured requests, key entities, deadlines, and required information from email conversations for downstream processing.",
    purpose: "Entity Extraction",
    category: "Automation",
    logoType: "request-extraction",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["intent-extraction"],
    capabilities: ["Entity extraction", "Deadline detection", "Requirement capture", "Action identification"],
    use: "Converting unstructured email content into structured data for further processing.",
    integrationsWith: ["gmail", "outlook"],
  },
  {
    id: "knowledge-retrieval",
    name: "Knowledge Retrieval",
    description: "Retrieves relevant information from approved knowledge sources and enterprise systems to support accurate email processing and response generation.",
    purpose: "Information Retrieval",
    category: "Knowledge",
    logoType: "knowledge-retrieval",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["information-retrieval"],
    capabilities: ["Knowledge search", "Policy lookup", "System data retrieval", "Source citation"],
    use: "Finding the information needed to accurately process or respond to an email.",
    integrationsWith: ["confluence"],
  },
  {
    id: "email-response-generator",
    name: "Email Response Generator",
    description: "Generates context-aware email responses using approved information, conversation history, and configured communication policies.",
    purpose: "Response Drafting",
    category: "Automation",
    logoType: "email-response-generator",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["response-generation"],
    capabilities: ["Draft generation", "Tone compliance", "Grounding in knowledge", "Personalization"],
    use: "Producing accurate, policy-compliant email responses for review or direct dispatch.",
    integrationsWith: ["gmail", "outlook"],
  },
  {
    id: "email-routing",
    name: "Email Routing",
    description: "Routes emails to the appropriate team, workflow, or service queue based on classification results and configured routing rules.",
    purpose: "Intelligent Email Routing",
    category: "Automation",
    logoType: "email-routing",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["workflow-action"],
    capabilities: ["Rules-based routing", "Skill-based assignment", "Queue management", "Escalation routing"],
    use: "Directing emails to the right team or workflow without manual triage.",
    integrationsWith: ["servicenow", "jira"],
  },
  {
    id: "task-creation",
    name: "Task Creation",
    description: "Converts actionable emails into structured tasks, tickets, or service requests in connected project and service management tools.",
    purpose: "Task Generation",
    category: "Automation",
    logoType: "task-creation",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["workflow-action"],
    capabilities: ["Task creation", "Ticket generation", "Field population", "Assignment"],
    use: "Turning actionable email content into tracked work items in connected systems.",
    integrationsWith: ["servicenow", "jira"],
  },
  {
    id: "email-followup",
    name: "Email Follow-up",
    description: "Automatically sends reminders and follow-up messages when configured time conditions or response triggers are met.",
    purpose: "Automated Follow-up",
    category: "Automation",
    logoType: "email-followup",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["tracking"],
    capabilities: ["Condition-based triggers", "Reminder dispatch", "Re-engagement sequences", "Escalation follow-up"],
    use: "Maintaining email engagement without manual follow-up effort.",
    integrationsWith: ["gmail", "outlook"],
  },
  {
    id: "email-audit",
    name: "Email Audit",
    description: "Tracks and logs automated email actions, response dispatches, routing decisions, and workflow activity for compliance and review.",
    purpose: "Audit & Compliance Logging",
    category: "Reporting",
    logoType: "email-audit",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["tracking"],
    capabilities: ["Action logging", "Response tracking", "Routing audit", "Compliance record"],
    use: "Maintaining a complete audit trail of all automated email activity.",
    integrationsWith: ["confluence"],
  },
  // Integrations
  {
    id: "gmail-email",
    name: "Gmail",
    description: "Connects to Gmail mailboxes to read, process, and send operational emails as part of the automation workflow.",
    purpose: "Email Platform",
    category: "Integration",
    logoType: "gmail",
    tier: "Integration · Tier 1",
    status: "Quick-start",
    workflowStages: ["email-intake", "response-generation", "tracking"],
    capabilities: ["Mailbox access", "Email sending", "Thread management"],
    method: "Gmail API",
    authentication: "OAuth 2.0",
    use: "Gmail-based email automation workflows.",
  },
  {
    id: "outlook-email",
    name: "Outlook",
    description: "Connects to Microsoft Outlook / Exchange mailboxes to read, process, and dispatch operational emails.",
    purpose: "Email Platform",
    category: "Integration",
    logoType: "outlook",
    tier: "Integration · Tier 1",
    status: "Quick-start",
    workflowStages: ["email-intake", "response-generation", "tracking"],
    capabilities: ["Mailbox access", "Email sending", "Calendar coordination"],
    method: "Microsoft Graph API",
    authentication: "OAuth 2.0",
    use: "Outlook / Exchange-based email automation workflows.",
  },
];

export const ALL_IT_EMAIL_PLUGINS = IT_EMAIL_PLUGINS;

// ─── IT Email Automation Stages ───────────────────────────────────────────────

export const IT_EMAIL_STAGES: SolutionStage[] = [
  {
    id: "email-intake",
    number: "01",
    title: "Incoming Email",
    description: "Receive and parse the email.",
    pluginIds: ["email-intake", "gmail-email", "outlook-email"],
  },
  {
    id: "classification",
    number: "02",
    title: "Email Classification",
    description: "Identify category, urgency, and routing.",
    pluginIds: ["email-classification"],
  },
  {
    id: "intent-extraction",
    number: "03",
    title: "Request Extraction",
    description: "Extract entities, requests, and deadlines.",
    pluginIds: ["request-extraction"],
  },
  {
    id: "information-retrieval",
    number: "04",
    title: "Information Retrieval",
    description: "Fetch relevant knowledge and data.",
    pluginIds: ["knowledge-retrieval"],
  },
  {
    id: "response-generation",
    number: "05",
    title: "Response Generation",
    description: "Generate a context-aware response.",
    pluginIds: ["email-response-generator"],
  },
  {
    id: "workflow-action",
    number: "06",
    title: "Action / Workflow",
    description: "Route email or create tasks.",
    pluginIds: ["email-routing", "task-creation"],
  },
  {
    id: "tracking",
    number: "07",
    title: "Tracking & Audit",
    description: "Monitor follow-ups and maintain audit log.",
    pluginIds: ["email-followup", "email-audit"],
  },
];
