import type { SolutionPlugin, SolutionStage } from "./types";

export const IT_SUPPORT_PLUGINS: SolutionPlugin[] = [
  {
    id: "it-request-intake",
    name: "IT Request Intake",
    description: "Understands employee IT requests from natural language and converts them into structured service requests with relevant fields populated.",
    purpose: "Request Structuring",
    category: "Request Management",
    logoType: "it-request-intake",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["request"],
    capabilities: ["NL understanding", "Field extraction", "Request structuring", "Urgency detection"],
    use: "Converting unstructured employee requests into actionable IT service records.",
    integrationsWith: ["servicenow", "jira"],
  },
  {
    id: "it-issue-classification",
    name: "Issue Classification",
    description: "Classifies IT issues by category, urgency, affected service, and request type to ensure correct routing and prioritization.",
    purpose: "Issue Classification",
    category: "Request Management",
    logoType: "it-issue-classification",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["classification"],
    capabilities: ["Category detection", "Urgency scoring", "Service mapping", "Type identification"],
    use: "Ensuring every IT request is correctly categorized before routing or resolution.",
    integrationsWith: ["servicenow", "jira"],
  },
  {
    id: "it-knowledge-search",
    name: "IT Knowledge Search",
    description: "Searches approved IT documentation and knowledge sources for troubleshooting instructions, known solutions, and relevant runbooks.",
    purpose: "IT Knowledge Retrieval",
    category: "Knowledge",
    logoType: "it-knowledge-search",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["knowledge"],
    capabilities: ["Runbook search", "Known issue matching", "Documentation retrieval", "Solution ranking"],
    use: "Surfacing the most relevant IT knowledge to resolve requests faster.",
    integrationsWith: ["confluence", "servicenow"],
  },
  {
    id: "troubleshooting-assistant",
    name: "Troubleshooting Assistant",
    description: "Guides users and agents through approved troubleshooting steps in sequence and recommends appropriate next actions based on responses.",
    purpose: "Guided Troubleshooting",
    category: "Request Management",
    logoType: "troubleshooting-assistant",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["troubleshooting"],
    capabilities: ["Step-by-step guidance", "Decision tree execution", "Response capture", "Next action suggestion"],
    use: "Walking users through structured troubleshooting before escalating to a technician.",
    integrationsWith: ["servicenow", "slack"],
  },
  {
    id: "incident-management",
    name: "Incident Management",
    description: "Creates, updates, assigns, and manages IT incidents throughout their lifecycle from detection to closure.",
    purpose: "Incident Lifecycle Management",
    category: "Request Management",
    logoType: "incident-management",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["ticket-creation", "resolution"],
    capabilities: ["Incident creation", "Status tracking", "Assignment", "Resolution recording"],
    use: "Maintaining a complete and up-to-date record of every IT incident.",
    integrationsWith: ["servicenow", "jira"],
  },
  {
    id: "service-request-management",
    name: "Service Request Management",
    description: "Creates and tracks employee requests for IT services such as software access, hardware, account changes, and configuration.",
    purpose: "Service Request Tracking",
    category: "Request Management",
    logoType: "service-request-management",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["ticket-creation"],
    capabilities: ["Request creation", "Status tracking", "Approver notification", "Fulfilment tracking"],
    use: "Managing the lifecycle of IT service requests from submission to fulfilment.",
    integrationsWith: ["servicenow", "jira"],
  },
  {
    id: "access-request",
    name: "Access Request",
    description: "Handles structured requests for access to applications, systems, and internal resources through defined approval and provisioning workflows.",
    purpose: "Access Provisioning",
    category: "Access Management",
    logoType: "access-request",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["ticket-creation", "resolution"],
    capabilities: ["Access request capture", "Approval routing", "Provisioning trigger", "Confirmation"],
    use: "Processing employee access requests through structured approval and provisioning flows.",
    integrationsWith: ["servicenow", "jira"],
  },
  {
    id: "it-escalation",
    name: "IT Escalation",
    description: "Escalates unresolved or high-priority IT issues to the appropriate technical team or on-call engineer with full context.",
    purpose: "Escalation Management",
    category: "Escalation",
    logoType: "it-escalation",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["escalation"],
    capabilities: ["Threshold detection", "On-call notification", "Context handoff", "Priority enforcement"],
    use: "Ensuring critical IT issues reach the right technical team before they impact the business.",
    integrationsWith: ["servicenow", "slack", "jira"],
  },
  {
    id: "it-notification",
    name: "IT Notification",
    description: "Sends employees automated updates about service request status, incident progress, approvals, and resolution confirmations.",
    purpose: "Employee Status Updates",
    category: "Communication",
    logoType: "it-notification",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["ticket-creation", "resolution", "escalation"],
    capabilities: ["Status notifications", "Approval confirmations", "Resolution alerts", "SLA warnings"],
    use: "Keeping employees informed about their IT requests without manual communication.",
    integrationsWith: ["slack", "microsoft-teams"],
  },
  {
    id: "it-summary",
    name: "IT Summary",
    description: "Summarizes the request, troubleshooting steps taken, resolution details, and any outstanding actions for the IT record.",
    purpose: "Resolution Summary",
    category: "Reporting",
    logoType: "it-summary",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["closure"],
    capabilities: ["Request summary", "Troubleshooting log", "Resolution documentation", "Action items"],
    use: "Creating a complete structured record of each IT request and its resolution.",
    integrationsWith: ["servicenow", "confluence"],
  },
  // ── Integrations ─────────────────────────────────────────────────────────
  {
    id: "servicenow-it",
    name: "ServiceNow",
    description: "Manages IT incidents, service requests, changes, and knowledge articles through ServiceNow's ITSM platform.",
    purpose: "ITSM Platform",
    category: "Integration",
    logoType: "servicenow",
    tier: "Integration · Tier 1",
    status: "Quick-start",
    workflowStages: ["request", "ticket-creation", "resolution", "closure"],
    capabilities: ["Incident management", "Service requests", "Change records", "Knowledge access"],
    method: "ServiceNow REST API",
    authentication: "OAuth 2.0",
    use: "Primary ITSM platform integration for IT support workflows.",
  },
  {
    id: "jira-it",
    name: "Jira",
    description: "Tracks IT issues, tasks, and service requests as Jira tickets with full workflow visibility for technical teams.",
    purpose: "Issue Tracking",
    category: "Integration",
    logoType: "jira",
    tier: "Integration · Tier 1",
    status: "Quick-start",
    workflowStages: ["ticket-creation", "escalation"],
    capabilities: ["Issue creation", "Status tracking", "Team assignment"],
    method: "Jira Cloud REST API",
    authentication: "OAuth 2.0",
    use: "Technical team issue tracking for IT requests and incidents.",
  },
];

export const ALL_IT_SUPPORT_PLUGINS = IT_SUPPORT_PLUGINS;

// ─── IT Support Workflow Stages ───────────────────────────────────────────────

export const IT_SUPPORT_STAGES: SolutionStage[] = [
  {
    id: "request",
    number: "01",
    title: "User Request",
    description: "Receive and structure the IT request.",
    pluginIds: ["it-request-intake", "it-notification"],
  },
  {
    id: "classification",
    number: "02",
    title: "Classification",
    description: "Classify the issue by type and urgency.",
    pluginIds: ["it-issue-classification", "servicenow-it"],
  },
  {
    id: "knowledge",
    number: "03",
    title: "Knowledge Search",
    description: "Find relevant documentation and solutions.",
    pluginIds: ["it-knowledge-search"],
  },
  {
    id: "troubleshooting",
    number: "04",
    title: "Troubleshooting",
    description: "Guide the user through resolution steps.",
    pluginIds: ["troubleshooting-assistant", "it-knowledge-search"],
  },
  {
    id: "ticket-creation",
    number: "05",
    title: "Ticket / Incident",
    description: "Create a formal incident or service record.",
    pluginIds: ["incident-management", "service-request-management", "access-request", "servicenow-it", "jira-it"],
  },
  {
    id: "resolution",
    number: "06",
    title: "Resolution",
    description: "Resolve the issue and confirm with the user.",
    pluginIds: ["incident-management", "it-notification", "it-summary"],
  },
  {
    id: "escalation",
    number: "07",
    title: "Escalation",
    description: "Escalate unresolved high-priority issues.",
    pluginIds: ["it-escalation", "servicenow-it", "it-notification"],
  },
  {
    id: "closure",
    number: "08",
    title: "Ticket Closure",
    description: "Document and close the resolved request.",
    pluginIds: ["it-summary", "it-notification"],
  },
];
