import type { SolutionPlugin, SolutionStage } from "./types";

export const IT_OPS_PLUGINS: SolutionPlugin[] = [
  {
    id: "service-catalog",
    name: "Service Catalog",
    description: "Provides structured access to available IT services and standardized service request templates for employees.",
    purpose: "Service Discovery",
    category: "Service Operations",
    logoType: "service-catalog",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["service-request"],
    capabilities: ["Catalog browsing", "Service lookup", "Request template selection", "Availability check"],
    use: "Presenting available IT services to employees in a structured, searchable form.",
    integrationsWith: ["servicenow", "jira"],
  },
  {
    id: "approval-workflow",
    name: "Approval Workflow",
    description: "Routes service requests through the required approval steps based on configurable business rules, requestor role, and request type.",
    purpose: "Approval Routing",
    category: "Service Operations",
    logoType: "approval-workflow",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["approval"],
    capabilities: ["Rule-based routing", "Approver notification", "Multi-level approval", "Rejection handling"],
    use: "Ensuring service requests go through the correct approval chain before fulfilment.",
    integrationsWith: ["servicenow", "slack", "microsoft-teams"],
  },
  {
    id: "service-provisioning",
    name: "Service Provisioning",
    description: "Triggers or coordinates approved service provisioning and configuration tasks in connected systems after approval is received.",
    purpose: "Automated Provisioning",
    category: "Automation",
    logoType: "service-provisioning",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["resource-action"],
    capabilities: ["Provisioning trigger", "System configuration", "Task coordination", "Completion confirmation"],
    use: "Automating the fulfilment of approved IT service requests.",
    integrationsWith: ["servicenow"],
  },
  {
    id: "asset-management",
    name: "Asset Management",
    description: "Retrieves and updates information about assigned IT assets, equipment inventory, and configuration items relevant to the service request.",
    purpose: "Asset Tracking",
    category: "Service Operations",
    logoType: "asset-management",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["resource-action"],
    capabilities: ["Asset lookup", "Assignment tracking", "Inventory update", "Configuration item access"],
    use: "Maintaining accurate asset records as part of IT service operations.",
    integrationsWith: ["servicenow"],
  },
  {
    id: "user-access-management",
    name: "User & Access Management",
    description: "Handles structured identity, account creation, permission assignment, and access-related service operations.",
    purpose: "Identity & Access Operations",
    category: "Access Management",
    logoType: "user-access-management",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["resource-action"],
    capabilities: ["Account creation", "Permission assignment", "Access modification", "Deprovisioning"],
    use: "Managing user identity and access as part of IT service fulfilment.",
    integrationsWith: ["servicenow"],
  },
  {
    id: "service-status",
    name: "Service Status",
    description: "Retrieves the current status of services, open requests, incidents, and operational activities to provide visibility across the service desk.",
    purpose: "Operational Visibility",
    category: "Service Operations",
    logoType: "service-status",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["status-tracking"],
    capabilities: ["Request status", "Incident status", "Service health", "Queue visibility"],
    use: "Providing real-time visibility into the status of IT services and outstanding work.",
    integrationsWith: ["servicenow", "jira"],
  },
  {
    id: "change-management",
    name: "Change Management",
    description: "Supports controlled IT changes by organizing change requests, approvals, implementation details, rollback plans, and completion status.",
    purpose: "Change Control",
    category: "Service Operations",
    logoType: "change-management",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["approval", "resource-action"],
    capabilities: ["Change request structuring", "Risk assessment", "Approval routing", "Implementation tracking"],
    use: "Managing IT changes through a structured, auditable approval and implementation process.",
    integrationsWith: ["servicenow", "jira"],
  },
  {
    id: "service-analytics",
    name: "Service Analytics",
    description: "Provides operational insights into service request volumes, fulfilment times, SLA performance, and IT team capacity.",
    purpose: "IT Operations Insights",
    category: "Reporting",
    logoType: "service-analytics",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["closure"],
    capabilities: ["Volume reporting", "SLA tracking", "Fulfilment analysis", "Capacity insights"],
    use: "Helping IT managers understand service performance and identify operational improvements.",
    integrationsWith: ["servicenow"],
  },
  // Integration
  {
    id: "servicenow-ops",
    name: "ServiceNow",
    description: "Central ITSM platform connection for service catalog, change management, asset tracking, and service request fulfilment.",
    purpose: "ITSM Platform",
    category: "Integration",
    logoType: "servicenow",
    tier: "Integration · Tier 1",
    status: "Quick-start",
    workflowStages: ["service-request", "approval", "resource-action", "status-tracking", "closure"],
    capabilities: ["Service catalog", "Change records", "Asset CMDB", "Request fulfilment"],
    method: "ServiceNow REST API",
    authentication: "OAuth 2.0",
    use: "Primary ITSM integration for service operations workflows.",
  },
];

export const ALL_IT_OPS_PLUGINS = IT_OPS_PLUGINS;

// ─── IT Service Operations Stages ────────────────────────────────────────────

export const IT_OPS_STAGES: SolutionStage[] = [
  {
    id: "service-request",
    number: "01",
    title: "Service Request",
    description: "Employee selects a service from the catalog.",
    pluginIds: ["service-catalog", "servicenow-ops"],
  },
  {
    id: "classification",
    number: "02",
    title: "Classification",
    description: "Categorize and prioritize the request.",
    pluginIds: ["service-catalog"],
  },
  {
    id: "approval",
    number: "03",
    title: "Approval",
    description: "Route request through required approvers.",
    pluginIds: ["approval-workflow", "change-management"],
  },
  {
    id: "resource-action",
    number: "04",
    title: "Resource / System Action",
    description: "Execute provisioning or configuration tasks.",
    pluginIds: ["service-provisioning", "asset-management", "user-access-management", "change-management"],
  },
  {
    id: "status-tracking",
    number: "05",
    title: "Status Tracking",
    description: "Monitor progress and communicate status.",
    pluginIds: ["service-status", "servicenow-ops"],
  },
  {
    id: "closure",
    number: "06",
    title: "Verification & Closure",
    description: "Confirm completion and close the record.",
    pluginIds: ["service-analytics", "service-status"],
  },
];
