import type { SolutionPlugin, SolutionStage, SolutionDef } from "./types";

// ─── Sales Plugins ────────────────────────────────────────────────────────────

export const SALES_PLUGINS: SolutionPlugin[] = [
  {
    id: "lead-capture",
    name: "Lead Capture",
    description: "Captures and organizes new leads from connected sources and adds them to the sales pipeline.",
    purpose: "Lead Ingestion",
    category: "Lead Management",
    logoType: "lead-capture",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["lead-capture"],
    capabilities: ["Multi-source ingestion", "Deduplication", "Pipeline entry", "Field mapping"],
    use: "Bringing new leads into the sales workflow from all connected channels.",
    integrationsWith: ["salesforce", "hubspot-crm"],
  },
  {
    id: "lead-enrichment",
    name: "Lead Enrichment",
    description: "Enriches lead records with company, role, contact, and other relevant business information to improve qualification accuracy.",
    purpose: "Data Enrichment",
    category: "Lead Management",
    logoType: "lead-enrichment",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["lead-capture", "lead-qualification"],
    capabilities: ["Company data enrichment", "Role identification", "Contact completion", "Industry tagging"],
    use: "Populating incomplete lead records before qualification begins.",
    integrationsWith: ["salesforce", "hubspot-crm"],
  },
  {
    id: "lead-qualification",
    name: "Lead Qualification",
    description: "Evaluates leads against configurable sales criteria and identifies prospects that are ready for direct sales engagement.",
    purpose: "Sales Readiness Assessment",
    category: "Qualification",
    logoType: "lead-qualification",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["lead-qualification"],
    capabilities: ["Criteria evaluation", "ICP matching", "Qualification scoring", "Disqualification flagging"],
    use: "Filtering leads to only those meeting minimum criteria before outreach.",
    integrationsWith: ["salesforce", "hubspot-crm"],
  },
  {
    id: "lead-scoring",
    name: "Lead Scoring",
    description: "Assigns a score to prospects based on engagement signals, profile information, and qualification criteria to prioritize the sales pipeline.",
    purpose: "Prospect Prioritization",
    category: "Qualification",
    logoType: "lead-scoring",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["lead-qualification", "outreach"],
    capabilities: ["Signal-based scoring", "Weighted criteria", "Score decay", "Priority ranking"],
    use: "Ranking qualified leads so sales reps focus on the highest-value opportunities first.",
    integrationsWith: ["salesforce", "hubspot-crm"],
  },
  {
    id: "sales-outreach",
    name: "Sales Outreach",
    description: "Creates and sends personalized outreach messages based on the prospect profile, account context, and configured sales messaging.",
    purpose: "Personalized Prospect Outreach",
    category: "Outreach",
    logoType: "sales-outreach",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["outreach"],
    capabilities: ["Message personalization", "Multi-channel dispatch", "A/B sequencing", "Reply detection"],
    use: "Engaging qualified prospects with contextually relevant outreach at scale.",
    integrationsWith: ["salesforce", "hubspot-crm", "gmail", "outlook"],
  },
  {
    id: "email-automation",
    name: "Email Automation",
    description: "Automates personalized sales emails, follow-up sequences, reminders, and re-engagement messages based on prospect behaviour.",
    purpose: "Sales Email Sequences",
    category: "Outreach",
    logoType: "email-automation",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["outreach", "follow-up"],
    capabilities: ["Sequence automation", "Behaviour triggers", "Follow-up scheduling", "Unsubscribe handling"],
    use: "Maintaining consistent engagement with prospects through automated email sequences.",
    integrationsWith: ["gmail", "outlook", "salesforce", "hubspot-crm"],
  },
  {
    id: "meeting-scheduler",
    name: "Meeting Scheduler",
    description: "Coordinates calendars and schedules meetings between sales representatives and prospects without manual back-and-forth.",
    purpose: "Meeting Coordination",
    category: "Scheduling",
    logoType: "meeting-scheduler",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["meeting"],
    capabilities: ["Availability matching", "Calendar sync", "Booking links", "Reminder dispatch"],
    use: "Removing coordination friction when scheduling prospect and customer meetings.",
    integrationsWith: ["google-calendar", "microsoft-teams", "salesforce"],
  },
  {
    id: "crm-update",
    name: "CRM Update",
    description: "Creates and updates leads, contacts, accounts, opportunities, and activity records in the CRM to keep sales data accurate.",
    purpose: "CRM Data Maintenance",
    category: "CRM",
    logoType: "crm-update",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["lead-capture", "lead-qualification", "outreach", "opportunity", "follow-up"],
    capabilities: ["Record creation", "Field updates", "Activity logging", "Stage progression"],
    use: "Keeping CRM data current throughout the sales workflow without manual entry.",
    integrationsWith: ["salesforce", "hubspot-crm"],
  },
  {
    id: "opportunity-management",
    name: "Opportunity Management",
    description: "Tracks opportunity stages, updates deal information, and helps maintain an accurate and up-to-date sales pipeline.",
    purpose: "Pipeline Management",
    category: "Pipeline",
    logoType: "opportunity-management",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["opportunity"],
    capabilities: ["Stage tracking", "Deal value updates", "Close date management", "Pipeline health"],
    use: "Maintaining deal accuracy and pipeline visibility throughout the sales cycle.",
    integrationsWith: ["salesforce", "hubspot-crm"],
  },
  {
    id: "sales-summary",
    name: "Sales Summary",
    description: "Summarizes sales activity, customer interactions, open opportunities, and important account updates for sales reps and managers.",
    purpose: "Activity Summarization",
    category: "Reporting",
    logoType: "sales-summary",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["follow-up", "reporting"],
    capabilities: ["Activity rollup", "Interaction summary", "Deal status overview", "Next action suggestions"],
    use: "Giving sales reps a clear view of their pipeline status and pending actions.",
    integrationsWith: ["salesforce", "hubspot-crm"],
  },
  {
    id: "sales-analytics",
    name: "Sales Analytics",
    description: "Analyzes sales activity, pipeline health, conversion rates, and performance data to provide actionable business insights.",
    purpose: "Sales Performance Insights",
    category: "Reporting",
    logoType: "sales-analytics",
    tier: "Native · AI Capability",
    status: "Active",
    workflowStages: ["reporting"],
    capabilities: ["Pipeline analytics", "Conversion analysis", "Win/loss reporting", "Rep performance"],
    use: "Giving sales managers the data needed to improve team performance and pipeline accuracy.",
    integrationsWith: ["salesforce", "hubspot-crm"],
  },
  // ── Integrations ─────────────────────────────────────────────────────────
  {
    id: "salesforce",
    name: "Salesforce",
    description: "Syncs leads, contacts, accounts, opportunities, and activity data between SoloBuildAI and Salesforce CRM.",
    purpose: "CRM · Salesforce",
    category: "Integration",
    logoType: "salesforce",
    tier: "Integration · Tier 1",
    status: "Quick-start",
    workflowStages: ["lead-capture", "lead-qualification", "outreach", "opportunity", "follow-up"],
    capabilities: ["Record sync", "Opportunity management", "Activity logging"],
    method: "Salesforce REST API",
    authentication: "OAuth 2.0",
    use: "Primary CRM integration for lead, contact and opportunity management.",
  },
  {
    id: "hubspot-crm",
    name: "HubSpot CRM",
    description: "Syncs contacts, deals, companies, and engagement data between SoloBuildAI and HubSpot CRM.",
    purpose: "CRM · HubSpot",
    category: "Integration",
    logoType: "hubspot-crm",
    tier: "Integration · Tier 1",
    status: "Quick-start",
    workflowStages: ["lead-capture", "lead-qualification", "outreach", "opportunity"],
    capabilities: ["Contact sync", "Deal tracking", "Engagement logging"],
    method: "HubSpot REST API",
    authentication: "OAuth 2.0",
    use: "CRM integration for teams using HubSpot as their sales platform.",
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    description: "Connects to Google Calendar for availability lookup and interview or meeting scheduling.",
    purpose: "Calendar & Scheduling",
    category: "Integration",
    logoType: "google-calendar",
    tier: "Integration · Tier 1",
    status: "Quick-start",
    workflowStages: ["meeting"],
    capabilities: ["Availability lookup", "Event creation", "Invite dispatch"],
    method: "Google Calendar API v3",
    authentication: "OAuth 2.0",
    use: "Meeting coordination with prospects and customers.",
  },
];

export const ALL_SALES_PLUGINS = SALES_PLUGINS;

// ─── Sales Workflow Stages ────────────────────────────────────────────────────

export const SALES_STAGES: SolutionStage[] = [
  {
    id: "lead-capture",
    number: "01",
    title: "Lead Capture",
    description: "Bring new leads into the pipeline.",
    pluginIds: ["lead-capture", "lead-enrichment", "crm-update"],
  },
  {
    id: "lead-qualification",
    number: "02",
    title: "Lead Qualification",
    description: "Evaluate and score prospects.",
    pluginIds: ["lead-enrichment", "lead-qualification", "lead-scoring", "crm-update"],
  },
  {
    id: "outreach",
    number: "03",
    title: "Sales Outreach",
    description: "Engage qualified prospects.",
    pluginIds: ["sales-outreach", "email-automation", "lead-scoring", "crm-update"],
  },
  {
    id: "meeting",
    number: "04",
    title: "Meeting & Scheduling",
    description: "Book meetings with prospects.",
    pluginIds: ["meeting-scheduler", "google-calendar", "crm-update"],
  },
  {
    id: "opportunity",
    number: "05",
    title: "Opportunity Management",
    description: "Track and advance deals.",
    pluginIds: ["opportunity-management", "crm-update", "salesforce"],
  },
  {
    id: "follow-up",
    number: "06",
    title: "Follow-up & Engagement",
    description: "Maintain momentum with prospects.",
    pluginIds: ["email-automation", "sales-summary", "crm-update"],
  },
  {
    id: "reporting",
    number: "07",
    title: "Sales Reporting",
    description: "Analyze performance and pipeline.",
    pluginIds: ["sales-summary", "sales-analytics", "salesforce", "hubspot-crm"],
  },
];

// ─── Sales Solution Definition ────────────────────────────────────────────────

export const SALES_SOLUTION: SolutionDef = {
  id: "sales",
  slug: "sales",
  name: "Sales",
  tagline: "Pipeline to close.",
  description: "AI agents to automate lead management, qualification, outreach, and pipeline operations — keeping your sales team focused on the conversations that matter.",
  eyebrow: "Solutions / Sales",
  heroQuote: "AI agents that qualify leads, write outreach, and keep your CRM accurate.",
  stats: [
    { value: "7",   label: "Sales Workflows" },
    { value: "11+", label: "Ready-to-use Plugins" },
    { value: "3+",  label: "Integrations" },
    { value: "60%", label: "Less Manual CRM Work" },
  ],
  processes: [
    {
      id: "lead-management",
      title: "Lead Management",
      description: "Capture, enrich and qualify leads automatically.",
      pluginCount: "4 plugins",
      integrationCount: "2 integrations",
      href: "/solutions/sales/lead-management",
      icon: "funnel",
      live: true,
    },
    {
      id: "sales-outreach",
      title: "Sales Outreach",
      description: "Personalized outreach and email sequences at scale.",
      pluginCount: "3 plugins",
      integrationCount: "2 integrations",
      href: "/solutions/sales/sales-outreach",
      icon: "mail",
    },
    {
      id: "pipeline-management",
      title: "Pipeline Management",
      description: "Track and advance opportunities through the sales cycle.",
      pluginCount: "3 plugins",
      integrationCount: "2 integrations",
      href: "/solutions/sales/opportunity-management",
      icon: "chart",
    },
    {
      id: "meeting-scheduling",
      title: "Meeting & Scheduling",
      description: "Book prospect and customer meetings without manual coordination.",
      pluginCount: "2 plugins",
      integrationCount: "2 integrations",
      href: "/solutions/sales/meeting-scheduling",
      icon: "calendar",
    },
  ],
  integrationNames: ["Salesforce", "HubSpot CRM", "Google Calendar", "Gmail", "Outlook", "Microsoft Teams"],
};
